name: Bug Report
description: Bug report template
title: "Bug: "
labels: ["bug"]
type: bug
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What went wrong? Where? Why is this important?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: What happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots / Logs
      description: Optional
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Browser:
        - Version:
        - Branch/Commit:
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else relevant.
    validations:
      required: false
